---
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: http://api.vcap.me:80/info
    body: !!null 
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      authorization:
      - 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
      content-type:
      - application/json
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/0.7.65
      date:
      - Sun, 06 Nov 2011 00:09:44 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      keep-alive:
      - timeout=20
      etag:
      - ! '"d5311babdfaea80ad353c85002fc2935"'
      cache-control:
      - max-age=0, private, must-revalidate
      x-ua-compatible:
      - IE=Edge
    body: !str
      str: ! '{"name":"vcap","build":2222,"support":"http://support.cloudfoundry.com","version":"0.999","description":"VMware''s
        Cloud Application Platform","allow_debug":false,"user":"user@vcap.me","limits":{"memory":2048,"app_uris":4,"services":16,"apps":20},"usage":{"memory":256,"apps":1,"services":0},"frameworks":{"spring":{"name":"spring","runtimes":[{"name":"java","version":"1.6","description":"Java
        6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]},"node":{"name":"node","runtimes":[{"name":"node","version":"0.4.5","description":"Node.js"}],"appservers":[],"detection":[{"*.js":"."}]},"sinatra":{"name":"sinatra","runtimes":[{"name":"ruby18","version":"1.8.7","description":"Ruby
        1.8.7"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9.2"}],"appservers":[{"name":"thin","description":"Thin"}],"detection":[{"*.rb":"require
        ''sinatra''|require \"sinatra\""},{"config/environment.rb":false}]},"lift":{"name":"lift","runtimes":[{"name":"java","version":"1.6","description":"Java
        6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]},"otp_rebar":{"name":"otp_rebar","runtimes":[{"name":"erlangR14B02","version":"R14B02","description":"Erlang
        R14B02"}],"appservers":[],"detection":[{"releases/*/*.rel":"."}]},"rails3":{"name":"rails3","runtimes":[{"name":"ruby18","version":"1.8.7","description":"Ruby
        1.8.7"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9.2"}],"appservers":[{"name":"thin","description":"Thin"}],"detection":[{"config/application.rb":true},{"config/environment.rb":true}]},"java_web":{"name":"java_web","runtimes":[{"name":"java","version":"1.6","description":"Java
        6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]},"grails":{"name":"grails","runtimes":[{"name":"java","version":"1.6","description":"Java
        6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]}}}'
      net_http_res: &70248465427620 !ruby/object:Net::HTTPOK
        http_version: '1.0'
        code: '200'
        message: OK
        header:
          server:
          - nginx/0.7.65
          date:
          - Sun, 06 Nov 2011 00:09:44 GMT
          content-type:
          - application/json; charset=utf-8
          transfer-encoding:
          - chunked
          connection:
          - keep-alive
          keep-alive:
          - timeout=20
          etag:
          - ! '"d5311babdfaea80ad353c85002fc2935"'
          cache-control:
          - max-age=0, private, must-revalidate
          x-ua-compatible:
          - IE=Edge
        body: !str
          str: ! '{"name":"vcap","build":2222,"support":"http://support.cloudfoundry.com","version":"0.999","description":"VMware''s
            Cloud Application Platform","allow_debug":false,"user":"user@vcap.me","limits":{"memory":2048,"app_uris":4,"services":16,"apps":20},"usage":{"memory":256,"apps":1,"services":0},"frameworks":{"spring":{"name":"spring","runtimes":[{"name":"java","version":"1.6","description":"Java
            6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]},"node":{"name":"node","runtimes":[{"name":"node","version":"0.4.5","description":"Node.js"}],"appservers":[],"detection":[{"*.js":"."}]},"sinatra":{"name":"sinatra","runtimes":[{"name":"ruby18","version":"1.8.7","description":"Ruby
            1.8.7"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9.2"}],"appservers":[{"name":"thin","description":"Thin"}],"detection":[{"*.rb":"require
            ''sinatra''|require \"sinatra\""},{"config/environment.rb":false}]},"lift":{"name":"lift","runtimes":[{"name":"java","version":"1.6","description":"Java
            6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]},"otp_rebar":{"name":"otp_rebar","runtimes":[{"name":"erlangR14B02","version":"R14B02","description":"Erlang
            R14B02"}],"appservers":[],"detection":[{"releases/*/*.rel":"."}]},"rails3":{"name":"rails3","runtimes":[{"name":"ruby18","version":"1.8.7","description":"Ruby
            1.8.7"},{"name":"ruby19","version":"1.9.2p180","description":"Ruby 1.9.2"}],"appservers":[{"name":"thin","description":"Thin"}],"detection":[{"config/application.rb":true},{"config/environment.rb":true}]},"java_web":{"name":"java_web","runtimes":[{"name":"java","version":"1.6","description":"Java
            6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]},"grails":{"name":"grails","runtimes":[{"name":"java","version":"1.6","description":"Java
            6"}],"appservers":[{"name":"tomcat","description":"Tomcat"}],"detection":[{"*.war":true}]}}}'
          net_http_res: *70248465427620
          args: &70248465799320
            :method: :get
            :url: http://api.vcap.me/info
            :payload: !!null 
            :headers:
              AUTHORIZATION: 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
              Content-Type: application/json
              Accept: application/json
          code: 200
          headers: &70248465426240
            :server: nginx/0.7.65
            :date: Sun, 06 Nov 2011 00:09:44 GMT
            :content_type: application/json; charset=utf-8
            :transfer_encoding: chunked
            :connection: keep-alive
            :keep_alive: timeout=20
            :etag: ! '"d5311babdfaea80ad353c85002fc2935"'
            :cache_control: max-age=0, private, must-revalidate
            :x_ua_compatible: IE=Edge
        read: true
        __read_body_previously_called: true
      args: *70248465799320
      code: 200
      headers: *70248465426240
    http_version: '1.1'
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: http://api.vcap.me:80/users
    body: !!null 
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      authorization:
      - 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
      content-type:
      - application/json
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 403
      message: Forbidden
    headers:
      server:
      - nginx/0.7.65
      date:
      - Sun, 06 Nov 2011 00:09:44 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      keep-alive:
      - timeout=20
      cache-control:
      - no-cache
      x-ua-compatible:
      - IE=Edge
    body: !str
      str: ! '{"code":200,"description":"Operation not permitted"}'
      net_http_res: &70248465071500 !ruby/object:Net::HTTPForbidden
        http_version: '1.0'
        code: '403'
        message: Forbidden
        header:
          server:
          - nginx/0.7.65
          date:
          - Sun, 06 Nov 2011 00:09:44 GMT
          content-type:
          - application/json; charset=utf-8
          transfer-encoding:
          - chunked
          connection:
          - keep-alive
          keep-alive:
          - timeout=20
          cache-control:
          - no-cache
          x-ua-compatible:
          - IE=Edge
        body: !str
          str: ! '{"code":200,"description":"Operation not permitted"}'
          net_http_res: *70248465071500
          args: &70248465322120
            :method: :get
            :url: http://api.vcap.me/users
            :payload: !!null 
            :headers:
              AUTHORIZATION: 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
              Content-Type: application/json
              Accept: application/json
          code: 403
          headers: &70248465070220
            :server: nginx/0.7.65
            :date: Sun, 06 Nov 2011 00:09:44 GMT
            :content_type: application/json; charset=utf-8
            :transfer_encoding: chunked
            :connection: keep-alive
            :keep_alive: timeout=20
            :cache_control: no-cache
            :x_ua_compatible: IE=Edge
        read: true
        __read_body_previously_called: true
      args: *70248465322120
      code: 403
      headers: *70248465070220
    http_version: '1.1'
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: http://api.vcap.me:80/services
    body: !!null 
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      authorization:
      - 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
      content-type:
      - application/json
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/0.7.65
      date:
      - Sun, 06 Nov 2011 00:09:44 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      keep-alive:
      - timeout=20
      etag:
      - ! '"d751713988987e9331980363e24189ce"'
      cache-control:
      - max-age=0, private, must-revalidate
      x-ua-compatible:
      - IE=Edge
    body: !str
      str: ! '[]'
      net_http_res: &70248464855400 !ruby/object:Net::HTTPOK
        http_version: '1.0'
        code: '200'
        message: OK
        header:
          server:
          - nginx/0.7.65
          date:
          - Sun, 06 Nov 2011 00:09:44 GMT
          content-type:
          - application/json; charset=utf-8
          transfer-encoding:
          - chunked
          connection:
          - keep-alive
          keep-alive:
          - timeout=20
          etag:
          - ! '"d751713988987e9331980363e24189ce"'
          cache-control:
          - max-age=0, private, must-revalidate
          x-ua-compatible:
          - IE=Edge
        body: !str
          str: ! '[]'
          net_http_res: *70248464855400
          args: &70248465066520
            :method: :get
            :url: http://api.vcap.me/services
            :payload: !!null 
            :headers:
              AUTHORIZATION: 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
              Content-Type: application/json
              Accept: application/json
          code: 200
          headers: &70248464843740
            :server: nginx/0.7.65
            :date: Sun, 06 Nov 2011 00:09:44 GMT
            :content_type: application/json; charset=utf-8
            :transfer_encoding: chunked
            :connection: keep-alive
            :keep_alive: timeout=20
            :etag: ! '"d751713988987e9331980363e24189ce"'
            :cache_control: max-age=0, private, must-revalidate
            :x_ua_compatible: IE=Edge
        read: true
        __read_body_previously_called: true
      args: *70248465066520
      code: 200
      headers: *70248464843740
    http_version: '1.1'
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: http://api.vcap.me:80/apps
    body: !!null 
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      authorization:
      - 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
      content-type:
      - application/json
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/0.7.65
      date:
      - Sun, 06 Nov 2011 00:09:45 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      keep-alive:
      - timeout=20
      etag:
      - ! '"d02a1191222309359a53d0f38436d7b8"'
      cache-control:
      - max-age=0, private, must-revalidate
      x-ua-compatible:
      - IE=Edge
    body: ! '[{"name":"app-mock-stopped","staging":{"model":"sinatra","stack":"ruby18"},"uris":["app-mock-stopped.vcap.me"],"instances":4,"runningInstances":null,"resources":{"memory":64,"disk":2048,"fds":256},"state":"STOPPED","services":[],"version":"946d7488427d90f0cef9a2993bd9a7520eec9a6e-1","env":[],"meta":{"debug":null,"version":6,"created":1320538185}},{"name":"app-mock-started","staging":{"model":"sinatra","stack":"ruby18"},"uris":["app-mock-started.vcap.me"],"instances":4,"runningInstances":4,"resources":{"memory":64,"disk":2048,"fds":256},"state":"STARTED","services":[],"version":"14b6fb795f1ff65355c2e06b91c21d997de40c49-1","env":[],"meta":{"debug":null,"version":51,"created":1320538185}}]'
    http_version: '1.1'
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :get
    uri: http://api.vcap.me:80/info/services
    body: !!null 
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      authorization:
      - 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
      content-type:
      - application/json
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 200
      message: OK
    headers:
      server:
      - nginx/0.7.65
      date:
      - Sun, 06 Nov 2011 00:09:45 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      keep-alive:
      - timeout=20
      etag:
      - ! '"10d071b91ca0499d990715e179ff8661"'
      cache-control:
      - max-age=0, private, must-revalidate
      x-ua-compatible:
      - IE=Edge
    body: !str
      str: ! '{"key-value":{"redis":{"2.2":{"id":1,"vendor":"redis","version":"2.2","tiers":{"free":{"options":{},"order":1}},"type":"key-value","description":"Redis
        key-value store service"}},"mongodb":{"1.8":{"id":3,"vendor":"mongodb","version":"1.8","tiers":{"free":{"options":{},"order":1}},"type":"key-value","description":"MongoDB
        NoSQL store"}}},"database":{"mysql":{"5.1":{"id":2,"vendor":"mysql","version":"5.1","tiers":{"free":{"options":{},"order":1}},"type":"database","description":"MySQL
        database service"}}}}'
      net_http_res: &70248464793020 !ruby/object:Net::HTTPOK
        http_version: '1.0'
        code: '200'
        message: OK
        header:
          server:
          - nginx/0.7.65
          date:
          - Sun, 06 Nov 2011 00:09:45 GMT
          content-type:
          - application/json; charset=utf-8
          transfer-encoding:
          - chunked
          connection:
          - keep-alive
          keep-alive:
          - timeout=20
          etag:
          - ! '"10d071b91ca0499d990715e179ff8661"'
          cache-control:
          - max-age=0, private, must-revalidate
          x-ua-compatible:
          - IE=Edge
        body: !str
          str: ! '{"key-value":{"redis":{"2.2":{"id":1,"vendor":"redis","version":"2.2","tiers":{"free":{"options":{},"order":1}},"type":"key-value","description":"Redis
            key-value store service"}},"mongodb":{"1.8":{"id":3,"vendor":"mongodb","version":"1.8","tiers":{"free":{"options":{},"order":1}},"type":"key-value","description":"MongoDB
            NoSQL store"}}},"database":{"mysql":{"5.1":{"id":2,"vendor":"mysql","version":"5.1","tiers":{"free":{"options":{},"order":1}},"type":"database","description":"MySQL
            database service"}}}}'
          net_http_res: *70248464793020
          args: &70248464841720
            :method: :get
            :url: http://api.vcap.me/info/services
            :payload: !!null 
            :headers:
              AUTHORIZATION: 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
              Content-Type: application/json
              Accept: application/json
          code: 200
          headers: &70248464791660
            :server: nginx/0.7.65
            :date: Sun, 06 Nov 2011 00:09:45 GMT
            :content_type: application/json; charset=utf-8
            :transfer_encoding: chunked
            :connection: keep-alive
            :keep_alive: timeout=20
            :etag: ! '"10d071b91ca0499d990715e179ff8661"'
            :cache_control: max-age=0, private, must-revalidate
            :x_ua_compatible: IE=Edge
        read: true
        __read_body_previously_called: true
      args: *70248464841720
      code: 200
      headers: *70248464791660
    http_version: '1.1'
- !ruby/struct:VCR::HTTPInteraction
  request: !ruby/struct:VCR::Request
    method: :post
    uri: http://api.vcap.me:80/services
    body: ! '{"type":"key-value","tier":"free","vendor":"redis","version":"2.2","name":"redis-mock"}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      authorization:
      - 04085b084922117573657240766361702e6d65063a0645546c2b079c0dbb4e2219b76dc61978db73a8263f70f1208a2cc743d5d6ba
      content-type:
      - application/json
      content-length:
      - '87'
  response: !ruby/struct:VCR::Response
    status: !ruby/struct:VCR::ResponseStatus
      code: 400
      message: Bad Request
    headers:
      server:
      - nginx/0.7.65
      date:
      - Sun, 06 Nov 2011 00:09:48 GMT
      content-type:
      - application/json; charset=utf-8
      transfer-encoding:
      - chunked
      connection:
      - keep-alive
      keep-alive:
      - timeout=20
      cache-control:
      - no-cache
      x-ua-compatible:
      - IE=Edge
    body: ! '{"description":"Validation failed: Alias has already been taken"}'
    http_version: '1.1'
